### ISSUE TITLE
[Installation with CocoaPods]Is there any one setup Sonar successfully with the guide on the official site ?

### ISSUE THREAD

**Issue by x4snowman** [facebook/Sonar#87]
I tried many ways, am still struggling fixing some compiler errors, even fork some repositories and modify the source code .If some one makes it work, could you share the steps? I think it will help many ones interested in Sonar.

**Comment by priteshrnandgaonkar** [comment]
Currently the master is broken, thats why you are not able to build, fix for this is coming soon. We will setup a proper CI so that internal changes cannot be broken in open source.

**Comment by x4snowman** [comment]
@priteshrnandgaonkar Thanks you. Can't wait try Sonar 😀

**Comment by priteshrnandgaonkar** [comment]
The current master is working. You can try it

**Comment by x4snowman** [comment]
@priteshrnandgaonkar Really appreciate your work. The whole build process is no problem but only does not find <SonarKit/SonarClient.h>.  I checked the "${PODS_ROOT}/Headers/Public/SonarKit" or "${PODS_ROOT}/Headers/Public", no SonarClient.h  found under these folder. There is a SonarClient.h under ${PODS_ROOT}/Headers/Public/Sonar. So I  changed the import to <Sonar/SonarClient.h>, but get a compiler error: 'iosfwd' file not found.

**Comment by priteshrnandgaonkar** [comment]
Hi, It should work now in master.Can you check?

**Comment by noahsark769** [comment]
@x4snowman are you trying to build your own project, or the `Sample` project inside the Sonar repo? 

If it's your own project, I think the issue is related to how Cocoapods exports public header files. I've actually got a fix for this incoming in the work I've done for #13 - should have a PR up tomorrow or Wednesday.

Also note that the iosfwd issue is the same one as #28.

**Comment by x4snowman** [comment]
@priteshrnandgaonkar Sorry to say it's still not work. According to the comment from @noahsark769 , I will wait your new submit and try again.

**Comment by x4snowman** [comment]
@noahsark769 It's a newly create a TestProject (Objective-c). Yeah, I have viewed all open issues. Hope everything will be fixed.

**Comment by noahsark769** [comment]
Yep, I bet this is the issue I was seeing. After #106 is merged, this should be fixed (and there will be a much easier to use Podfile configuration after #107 is merged).

**Comment by x4snowman** [comment]
@noahsark769 Hi,  Any good news?

**Comment by noahsark769** [comment]
@x4snowman not yet unfortunately, there are still a couple of issues outstanding in #106

**Comment by priteshrnandgaonkar** [comment]
@x4snowman, the current setup should work for objective-c based project.

**Comment by x4snowman** [comment]
@priteshrnandgaonkar @noahsark769 Hey guys, really appreciate your work to fix all issues. Yes, have already run an objc-base project. But, we need fix one more little problem with `'FBDefines/FBMacros.h' file not found`. I added the "${PODS_ROOT}/SonarKit/iOS/SonarKit" into the search path, and everything is ok. I think you can add it to the public header search path.

And thanks for your great work again. Sonar will be a powerful and interesting tool.

**Comment by noahsark769** [comment]
@x4snowman yup I ran into that FBMacros issue also. For what it's worth, that should be fixed in #106 too.
